CREATE TABLE `elm_hc_report_data` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `customer_name` varchar(200) NOT NULL COMMENT '客户名称',
  `customer_short` varchar(50) NOT NULL COMMENT '客户简称',
  `agent_name` varchar(200) NOT NULL COMMENT '代理名称',
  `agent_short` varchar(50) NOT NULL COMMENT '代理简称',
  `media_platform_name` varchar(100) NOT NULL COMMENT '媒体平台名称',
  `media_adv_id` varchar(100) NOT NULL COMMENT '媒体账户ID',
  `media_adv_name` varchar(200) NOT NULL COMMENT '媒体账户名称',
  `huichuan_adv_id` bigint NOT NULL DEFAULT '0' COMMENT '汇川账户ID',
  `cost` decimal(12,4) DEFAULT '0.0000' COMMENT '消费',
  `show_num` bigint DEFAULT '0' COMMENT '展示数',
  `click_num` bigint DEFAULT '0' COMMENT '点击数',
  `convert_num` bigint DEFAULT '0' COMMENT '转化数',
  `deep_convert_num` int DEFAULT '0' COMMENT '深度转化数',
  `convert_type` varchar(50) DEFAULT '' COMMENT '转化类型',
  `deep_convert_type` varchar(50) DEFAULT '' COMMENT '深度转化类型',
  `redirect_num` int DEFAULT '0' COMMENT '调起数',
  `pay_num` int DEFAULT '0' COMMENT '付费数',
  `dt` varchar(8) NOT NULL COMMENT '日期，格式：yyyyMMdd',
  `hh` varchar(2) NOT NULL DEFAULT '' COMMENT '小时，格式：hh',
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_media_adv_dt` (`media_adv_id`,`dt`,`hh`) COMMENT '唯一约束：防止重复数据',
  KEY `idx_dt` (`dt`) COMMENT '按日期查询索引',
  KEY `idx_customer_short` (`customer_short`) COMMENT '按客户简称查询索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='饿了么汇川报表数据';
