// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

// =============== 返点配置 ===============

// 创建返点配置请求
type CreateRebateReq struct {
	Subject     string  `json:"subject" binding:"required"`      // 主体：新杰、晴川、美数、魔米、归流
	Port        string  `json:"port" binding:"required"`         // 端口：优居、至也、各界
	RebateRate  float64 `json:"rebate_rate" binding:"required"`  // 返点率：如0.025表示2.5%
	SubjectType int8    `json:"subject_type" binding:"required"` // 主体类型：1-京东主体, 2-三方主体
	Remark      string  `json:"remark"`                          // 备注
}

// 更新返点配置请求
type UpdateRebateReq struct {
	ID          uint    `json:"id" binding:"required"`
	Subject     string  `json:"subject" binding:"required"`
	Port        string  `json:"port" binding:"required"`
	RebateRate  float64 `json:"rebate_rate" binding:"required"`
	SubjectType int8    `json:"subject_type" binding:"required"`
	Remark      string  `json:"remark"`
}

// 删除返点配置请求
type DeleteRebateReq struct {
	ID uint `json:"id" binding:"required"`
}

// 返点配置响应
type RebateResp struct {
	ID          uint    `json:"id"`
	Subject     string  `json:"subject"`
	Port        string  `json:"port"`
	RebateRate  float64 `json:"rebate_rate"`
	SubjectType int8    `json:"subject_type"`
	Remark      string  `json:"remark"`
	UpdateTime  string  `json:"update_time"`
	CreateTime  string  `json:"create_time"`
}

// 返点配置列表响应
type RebateListResp struct {
	Code    int           `json:"code"`
	Message string        `json:"message"`
	Data    []*RebateResp `json:"data"`
}

// 返点配置通用响应
type RebateCommonResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// =============== 服务费配置 ===============

// 创建服务费配置请求
type CreateServiceFeeReq struct {
	ServiceProvider string  `json:"service_provider" binding:"required"` // 服务商名称：通途、蚁行、创效、凯旋、星河、云谷、美数
	FeeRate         float64 `json:"fee_rate" binding:"required"`         // 服务费率：如0.04表示4%
	Remark          string  `json:"remark"`                              // 备注
}

// 更新服务费配置请求
type UpdateServiceFeeReq struct {
	ID              uint    `json:"id" binding:"required"`
	ServiceProvider string  `json:"service_provider" binding:"required"`
	FeeRate         float64 `json:"fee_rate" binding:"required"`
	Remark          string  `json:"remark"`
}

// 删除服务费配置请求
type DeleteServiceFeeReq struct {
	ID uint `json:"id" binding:"required"`
}

// 服务费配置响应
type ServiceFeeResp struct {
	ID              uint    `json:"id"`
	ServiceProvider string  `json:"service_provider"`
	FeeRate         float64 `json:"fee_rate"`
	Remark          string  `json:"remark"`
	UpdateTime      string  `json:"update_time"`
	CreateTime      string  `json:"create_time"`
}

// 服务费配置列表响应
type ServiceFeeListResp struct {
	Code    int               `json:"code"`
	Message string            `json:"message"`
	Data    []*ServiceFeeResp `json:"data"`
}

// 服务费配置通用响应
type ServiceFeeCommonResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// =============== 任务类型配置 ===============

// 创建任务类型请求
type CreateTaskTypeReq struct {
	Name            string  `json:"name" binding:"required"`             // 任务名称，如：app、首购
	Code            string  `json:"code" binding:"required"`             // 任务编码
	SettlementPrice float64 `json:"settlement_price" binding:"required"` // 结算单价
	Media           string  `json:"media" binding:"required"`            // 媒体平台，如：巨量
	Status          int8    `json:"status"`                              // 状态：1-启用, 0-停用
}

// 更新任务类型请求
type UpdateTaskTypeReq struct {
	ID              uint    `json:"id" binding:"required"`
	Name            string  `json:"name" binding:"required"`
	Code            string  `json:"code" binding:"required"`
	SettlementPrice float64 `json:"settlement_price" binding:"required"`
	Media           string  `json:"media" binding:"required"`
	Status          int8    `json:"status"`
}

// 删除任务类型请求
type DeleteTaskTypeReq struct {
	ID uint `json:"id" binding:"required"`
}

// 任务类型响应
type TaskTypeResp struct {
	ID              uint    `json:"id"`
	Name            string  `json:"name"`
	Code            string  `json:"code"`
	SettlementPrice float64 `json:"settlement_price"`
	Media           string  `json:"media"`
	Status          int8    `json:"status"`
	CreateTime      string  `json:"create_time"`
	UpdateTime      string  `json:"update_time"`
}

// 任务类型列表响应
type TaskTypeListResp struct {
	Code    int             `json:"code"`
	Message string          `json:"message"`
	Data    []*TaskTypeResp `json:"data"`
}

// 任务类型通用响应
type TaskTypeCommonResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}
