// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

// 更新dhhCookie请求
type UpdateDhhCookieReq struct {
	Token     string `json:"cookie"`
	CsrfToken string `json:"csrfToken"`
}

// 更新京橙Cookie响应
type UpdateDhhCookieResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// 获取京橙Cookie响应
type GetDhhCookieResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    string `json:"cookie"`
	Csrf    string `json:"csrf"`
}
