// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

// =============== 汇川饿了么数据报表 ===============

// 创建汇川饿了么数据报表请求
type CreateElmHcReportReq struct {
	CustomerName      string `json:"customer_name" binding:"required"`       // 客户名称
	CustomerShort     string `json:"customer_short" binding:"required"`      // 客户简称
	AgentName         string `json:"agent_name" binding:"required"`          // 代理名称
	AgentShort        string `json:"agent_short" binding:"required"`         // 代理简称
	MediaPlatformName string `json:"media_platform_name" binding:"required"` // 媒体平台名称
	RedirectNum       int    `json:"redirect_num"`                           // 调起数
	PayNum            int    `json:"pay_num"`                                // 付费数
}

// 更新汇川饿了么数据报表请求
type UpdateElmHcReportReq struct {
	ID                int64  `json:"id" binding:"required"`
	CustomerName      string `json:"customer_name" binding:"required"`
	CustomerShort     string `json:"customer_short" binding:"required"`
	AgentName         string `json:"agent_name" binding:"required"`
	AgentShort        string `json:"agent_short" binding:"required"`
	MediaPlatformName string `json:"media_platform_name" binding:"required"`
	RedirectNum       int    `json:"redirect_num"`
	PayNum            int    `json:"pay_num"`
}

// 删除汇川饿了么数据报表请求
type DeleteElmHcReportReq struct {
	ID int64 `json:"id" binding:"required"`
}

// 汇川饿了么数据报表响应
type ElmHcReportResp struct {
	ID                int64  `json:"id"`
	CustomerName      string `json:"customer_name"`
	CustomerShort     string `json:"customer_short"`
	AgentName         string `json:"agent_name"`
	AgentShort        string `json:"agent_short"`
	MediaPlatformName string `json:"media_platform_name"`
	RedirectNum       int    `json:"redirect_num"`
	PayNum            int    `json:"pay_num"`
	CreateTime        string `json:"create_time"`
	UpdateTime        string `json:"update_time"`
}

// 汇川饿了么数据报表列表响应
type ElmHcReportListResp struct {
	Code    int                `json:"code"`
	Message string             `json:"message"`
	Data    []*ElmHcReportResp `json:"data"`
}

// 汇川饿了么数据报表通用响应
type ElmHcReportCommonResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// =============== 汇川饿了么媒体账户 ===============

// 创建汇川饿了么媒体账户请求
type CreateElmHcMediaReq struct {
	PerformanceID int64  `json:"performance_id" binding:"required"`  // 客户ID
	MediaAdvId    string `json:"media_adv_id" binding:"required"`    // 媒体账户ID
	MediaAdvName  string `json:"media_adv_name" binding:"required"`  // 媒体账户名称
	HuichuanAdvId int64  `json:"huichuan_adv_id" binding:"required"` // 汇川账户ID
}

// 删除汇川饿了么媒体账户请求
type DeleteElmHcMediaReq struct {
	ID int64 `json:"id" binding:"required"`
}

// 汇川饿了么媒体账户响应
type ElmHcMediaResp struct {
	ID            int64  `json:"id"`
	PerformanceID int64  `json:"performance_id"`
	MediaAdvId    string `json:"media_adv_id"`
	MediaAdvName  string `json:"media_adv_name"`
	HuichuanAdvId int64  `json:"huichuan_adv_id"`
	CreateTime    string `json:"create_time"`
	UpdateTime    string `json:"update_time"`
}

// 汇川饿了么媒体账户列表响应
type ElmHcMediaListResp struct {
	Code    int               `json:"code"`
	Message string            `json:"message"`
	Data    []*ElmHcMediaResp `json:"data"`
}

// 汇川饿了么媒体账户通用响应
type ElmHcMediaCommonResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}
