// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

// =============== 汇川饿了么账户报表 ===============

// 创建汇川饿了么账户报表请求
type CreateElmHcMediaReportReq struct {
	MediaAdvId    string `json:"media_adv_id" binding:"required"`    // 媒体账户ID
	MediaAdvName  string `json:"media_adv_name" binding:"required"`  // 媒体账户名称
	HuichuanAdvId int64  `json:"huichuan_adv_id" binding:"required"` // 汇川账户ID
}

// 更新汇川饿了么账户报表请求
type UpdateElmHcMediaReportReq struct {
	ID            int64  `json:"id" binding:"required"`
	MediaAdvId    string `json:"media_adv_id" binding:"required"`
	MediaAdvName  string `json:"media_adv_name" binding:"required"`
	HuichuanAdvId int64  `json:"huichuan_adv_id" binding:"required"`
}

// 删除汇川饿了么账户报表请求
type DeleteElmHcMediaReportReq struct {
	ID int64 `json:"id" binding:"required"`
}

// 汇川饿了么账户报表响应
type ElmHcMediaReportResp struct {
	ID            int64  `json:"id"`
	MediaAdvId    string `json:"media_adv_id"`
	MediaAdvName  string `json:"media_adv_name"`
	HuichuanAdvId int64  `json:"huichuan_adv_id"`
	CreateTime    string `json:"create_time"`
	UpdateTime    string `json:"update_time"`
}

// 汇川饿了么账户报表列表响应
type ElmHcMediaReportListResp struct {
	Code    int                     `json:"code"`
	Message string                  `json:"message"`
	Data    []*ElmHcMediaReportResp `json:"data"`
}

// 汇川饿了么账户报表通用响应
type ElmHcMediaReportCommonResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}
