// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

// 更新京橙复投Cookie请求
type UpdateJingchengFutouCookieReq struct {
	Token        string `json:"cookie"`
	RefreshToken string `json:"csrfToken"`
}

// 更新京橙复投Cookie响应
type UpdateJingchengFutouCookieResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// 获取京橙复投Cookie响应
type GetJingchengFutouCookieResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    string `json:"data"`
}
