// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

// 更新巨量Cookie请求
type UpdateJuliangCookieReq struct {
	Cookie    string `json:"cookie"`
	CsrfToken string `json:"csrfToken"`
}

// 更新巨量Cookie响应
type UpdateJuliangCookieResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// 巨量 API 响应结构
type JuliangApiResponse struct {
	Code      int                    `json:"code"`
	Msg       string                 `json:"msg"`
	RequestId string                 `json:"request_id"`
	Data      JuliangApiResponseData `json:"data"`
	Extra     map[string]interface{} `json:"extra"`
}

type JuliangApiResponseData struct {
	DataList     []JuliangAccountData `json:"data_list"`
	TotalMetrics JuliangMetrics       `json:"total_metrics"`
	Pagination   JuliangPagination    `json:"pagination"`
	DownloadId   string               `json:"download_id"`
}

type JuliangAccountData struct {
	AdvertiserId     int64  `json:"advertiser_id"`
	AdvertiserName   string `json:"advertiser_name"`
	AdvertiserRemark string `json:"advertiser_remark"`
	StatCost         string `json:"stat_cost"`       // 消耗
	StatCashCost     string `json:"stat_cash_cost"`  // 现金消耗
	ShowCnt          string `json:"show_cnt"`        // 曝光数
	ClickCnt         string `json:"click_cnt"`       // 点击数
	Ctr              string `json:"ctr"`             // 点击率
	ConvertCnt       string `json:"convert_cnt"`     // 转化数
	ConversionCost   string `json:"conversion_cost"` // 转化成本
	ConversionRate   string `json:"conversion_rate"` // 转化率
}

type JuliangMetrics struct {
	StatCost       string `json:"stat_cost"`       // 总消耗
	StatCashCost   string `json:"stat_cash_cost"`  // 总现金消耗
	ShowCnt        string `json:"show_cnt"`        // 总曝光数
	ClickCnt       string `json:"click_cnt"`       // 总点击数
	Ctr            string `json:"ctr"`             // 总点击率
	ConvertCnt     string `json:"convert_cnt"`     // 总转化数
	ConversionCost string `json:"conversion_cost"` // 总转化成本
	ConversionRate string `json:"conversion_rate"` // 总转化率
}

type JuliangPagination struct {
	Page    int  `json:"page"`
	Limit   int  `json:"limit"`
	Total   int  `json:"total"`
	HasMore bool `json:"hasMore"`
}
