// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

// 更新巨量Cookie请求
type UpdateJuliangCookieReq struct {
	Cookie    string `json:"cookie"`
	CsrfToken string `json:"csrfToken"`
}

// 更新巨量Cookie响应
type UpdateJuliangCookieResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// 更新竞成Cookie请求
type UpdateJingchengCookieReq struct {
	Token        string `json:"cookie"`
	RefreshToken string `json:"csrfToken"`
}

// 更新竞成Cookie响应
type UpdateJingchengCookieResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// 巨量 API 响应结构
type JuliangApiResponse struct {
	Code      int                    `json:"code"`
	Msg       string                 `json:"msg"`
	RequestId string                 `json:"request_id"`
	Data      JuliangApiResponseData `json:"data"`
	Extra     map[string]interface{} `json:"extra"`
}

type JuliangApiResponseData struct {
	DataList        []JuliangAccountData `json:"data_list"`
	TotalMetrics    JuliangMetrics       `json:"total_metrics"`
	Pagination      JuliangPagination    `json:"pagination"`
	DownloadId      string               `json:"download_id"`
	DownloadChannel int                  `json:"download_channel"`
}

type JuliangAccountData struct {
	AdvertiserId     int64  `json:"advertiser_id"`
	AdvertiserName   string `json:"advertiser_name"`
	AdvertiserRemark string `json:"advertiser_remark"`
	StatCost         string `json:"stat_cost"`       // 消耗
	StatCashCost     string `json:"stat_cash_cost"`  // 现金消耗
	ShowCnt          string `json:"show_cnt"`        // 曝光数
	ClickCnt         string `json:"click_cnt"`       // 点击数
	Ctr              string `json:"ctr"`             // 点击率
	ConvertCnt       string `json:"convert_cnt"`     // 转化数
	ConversionCost   string `json:"conversion_cost"` // 转化成本
	ConversionRate   string `json:"conversion_rate"` // 转化率
}

type JuliangMetrics struct {
	StatCost       string `json:"stat_cost"`       // 总消耗
	StatCashCost   string `json:"stat_cash_cost"`  // 总现金消耗
	ShowCnt        string `json:"show_cnt"`        // 总曝光数
	ClickCnt       string `json:"click_cnt"`       // 总点击数
	Ctr            string `json:"ctr"`             // 总点击率
	ConvertCnt     string `json:"convert_cnt"`     // 总转化数
	ConversionCost string `json:"conversion_cost"` // 总转化成本
	ConversionRate string `json:"conversion_rate"` // 总转化率
}

type JuliangPagination struct {
	Page    int  `json:"page"`
	Limit   int  `json:"limit"`
	Total   int  `json:"total"`
	HasMore bool `json:"hasMore"`
}

// 归因数据响应结构
type AttributionResponse struct {
	Code    int             `json:"code"`
	Message string          `json:"message"`
	Data    AttributionData `json:"data"`
}

type AttributionData struct {
	Date          string                      `json:"date"`
	TotalRequests map[string]int64            `json:"total_requests"`
	ErrorCounts   map[string]map[string]int64 `json:"error_counts"` // advertiser_id -> error_type -> count
	Summary       AttributionSummary          `json:"summary"`
}

type AttributionSummary struct {
	TotalRequestCount int64            `json:"total_request_count"`
	TotalErrorCount   int64            `json:"total_error_count"`
	ErrorTypes        map[string]int64 `json:"error_types"`
}

// 下载任务列表响应
type DownloadTaskListResponse struct {
	Code      int                    `json:"code"`
	Msg       string                 `json:"msg"`
	RequestId string                 `json:"request_id"`
	Data      DownloadTaskListData   `json:"data"`
	Extra     map[string]interface{} `json:"extra"`
}

type DownloadTaskListData struct {
	Total    int            `json:"total"`
	List     []DownloadTask `json:"list"`
	BaseResp BaseResp       `json:"BaseResp"`
}

type BaseResp struct {
	StatusMessage string `json:"StatusMessage"`
	StatusCode    int    `json:"StatusCode"`
}

type DownloadTask struct {
	SchedulerId         int64             `json:"schedulerId"`
	TaskId              string            `json:"taskId"`
	UserId              int64             `json:"userId"`
	AppKey              int               `json:"appKey"`
	SchedulerType       int               `json:"schedulerType"`
	SchedulerTypeName   string            `json:"schedulerTypeName"`
	SchedulerStatus     int               `json:"schedulerStatus"`
	SchedulerStatusName string            `json:"schedulerStatusName"`
	TaskCreateTime      string            `json:"taskCreateTime"`
	TaskExpireTime      string            `json:"taskExpireTime"`
	ExtraKV             map[string]string `json:"extraKV"`
	CanRetry            bool              `json:"canRetry"`
}
