// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

// 快手账户报表请求
type KsAccountReportReq struct {
	StartDate           string `json:"start_date"`
	EndDate             string `json:"end_date"`
	AdvertiserId        int64  `json:"advertiser_id"`
	TemporalGranularity string `json:"temporal_granularity,omitempty"`
}

// 快手账户报表响应
type KsAccountReportResp struct {
	Code    int                 `json:"code"`
	Message string              `json:"message"`
	Data    []*KsReportDataItem `json:"data"`
}

// 快手报表数据项
type KsReportDataItem struct {
	Time            string  `json:"时间"`    // 时间
	Account         string  `json:"账户"`    // 账户名称
	Charge          float64 `json:"消耗"`    // 消耗 * 1.2
	Activation      int64   `json:"注册转化数"` // 注册转化数（激活数）
	ConversionCost  float64 `json:"转化成本"`  // 转化成本 * 1.2
	AdShow          int64   `json:"曝光"`    // 曝光数
	Bclick          int64   `json:"点击"`    // 点击数
	ConversionRatio string  `json:"转化率"`   // 转化率（格式化为百分比字符串）
}

// 快手 API 原始响应结构
type KsApiResponse struct {
	Code      int               `json:"code"`
	Message   string            `json:"message"`
	RequestId string            `json:"request_id"`
	Data      KsApiResponseData `json:"data"`
}

type KsApiResponseData struct {
	Empty      bool                `json:"empty"`
	TotalCount int                 `json:"total_count"`
	Details    []KsApiReportDetail `json:"details"`
}

type KsApiReportDetail struct {
	Charge          float64 `json:"charge"`           // 消耗
	AdShow          float64 `json:"ad_show"`          // 曝光数
	Bclick          int64   `json:"bclick"`           // 点击数
	Activation      int64   `json:"activation"`       // 激活数
	ConversionCost  float64 `json:"conversion_cost"`  // 转化成本
	ConversionRatio float64 `json:"conversion_ratio"` // 转化率
	StatDatetime    string  `json:"stat_datetime"`    // 统计时间
	StatDate        string  `json:"stat_date"`        // 统计日期
}
