package types

// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

// Token 刷新响应
type TokenRefreshResponse struct {
	Code      int                      `json:"code"`
	Message   string                   `json:"message"`
	RequestId string                   `json:"request_id"`
	Data      TokenRefreshResponseData `json:"data"`
}

type TokenRefreshResponseData struct {
	AccessToken           string `json:"access_token"`
	RefreshToken          string `json:"refresh_token"`
	ExpiresIn             int64  `json:"expires_in"`
	AccessTokenExpiresIn  int64  `json:"access_token_expires_in"`
	RefreshTokenExpiresIn int64  `json:"refresh_token_expires_in"`
}
