// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

// 对外返回的请求和响应结构
type KsAccountReportReq struct {
	StartDate           string `json:"start_date"`
	EndDate             string `json:"end_date"`
	AdvertiserId        int64  `json:"advertiser_id"`
	TemporalGranularity string `json:"temporal_granularity,omitempty"`
}

type KsAccountReportResp struct {
	Code    int                 `json:"code"`
	Message string              `json:"message"`
	Data    []*KsReportDataItem `json:"data"`
}

type KsReportDataItem struct {
	Charge          float64 `json:"charge"`           // 消耗 * 1.5
	AdShow          float64 `json:"ad_show"`          // 曝光数
	Bclick          int64   `json:"bclick"`           // 点击数
	Activation      int64   `json:"activation"`       // 激活数
	ConversionCost  float64 `json:"conversion_cost"`  // 转化成本 * 1.5
	ConversionRatio float64 `json:"conversion_ratio"` // 转化率 * 100
}

// 快手 API 原始响应结构
type KsApiResponse struct {
	Code      int               `json:"code"`
	Message   string            `json:"message"`
	RequestId string            `json:"request_id"`
	Data      KsApiResponseData `json:"data"`
}

type KsApiResponseData struct {
	Empty      bool                `json:"empty"`
	TotalCount int                 `json:"total_count"`
	Details    []KsApiReportDetail `json:"details"`
}

type KsApiReportDetail struct {
	Charge          float64 `json:"charge"`           // 消耗
	AdShow          float64 `json:"ad_show"`          // 曝光数
	Bclick          int64   `json:"bclick"`           // 点击数
	Activation      int64   `json:"activation"`       // 激活数
	ConversionCost  float64 `json:"conversion_cost"`  // 转化成本
	ConversionRatio float64 `json:"conversion_ratio"` // 转化率
	StatDate        string  `json:"stat_date"`        // 统计日期
}
