// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"fmt"
	"net/http"
	"path/filepath"

	config "media_report/service/api/internal/handler/config"
	download "media_report/service/api/internal/handler/download"
	fz "media_report/service/api/internal/handler/fz"
	report "media_report/service/api/internal/handler/report"
	tanx "media_report/service/api/internal/handler/tanx"
	ulink "media_report/service/api/internal/handler/ulink"
	update "media_report/service/api/internal/handler/update"
	zfb "media_report/service/api/internal/handler/zfb"
	"media_report/service/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// 添加静态文件服务
	webDir := filepath.Join("..", "..", "web")

	// 静态文件服务（使用通配符路由）
	server.AddRoute(rest.Route{
		Method: http.MethodGet,
		Path:   "/web/:path",
		Handler: func(w http.ResponseWriter, r *http.Request) {
			// 直接使用原始 URL 路径，去掉 /web/ 前缀
			requestPath := r.URL.Path
			if len(requestPath) > 5 { // 长度大于 "/web/"
				filename := requestPath[5:] // 去掉 "/web/" 前缀
				filePath := filepath.Join(webDir, filename)

				// 添加日志记录
				fmt.Printf("[Static File] Serving: %s -> %s\n", requestPath, filePath)

				// 设置正确的Content-Type
				if filepath.Ext(filename) == ".html" {
					w.Header().Set("Content-Type", "text/html; charset=utf-8")
				}

				http.ServeFile(w, r, filePath)
			} else {
				http.NotFound(w, r)
			}
		},
	})

	// 添加 web 目录下所有文件的静态文件服务（匹配所有子路径）
	server.AddRoute(rest.Route{
		Method: http.MethodGet,
		Path:   "/",
		Handler: func(w http.ResponseWriter, r *http.Request) {
			http.ServeFile(w, r, filepath.Join(webDir, "index.html"))
		},
	})

	// 菜鸟账户路由
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/cainiao_advertiser/list",
				Handler: config.CainiaoAdvertiserListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/cainiao_advertiser/add",
				Handler: config.CainiaoAdvertiserAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/cainiao_advertiser/delete",
				Handler: config.CainiaoAdvertiserDeleteHandler(serverCtx),
			},
		},
	)

	// 飞猪媒体账户路由
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/fz_advertiser/list",
				Handler: fz.FzAdvertiserListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/fz_advertiser/add",
				Handler: fz.FzAdvertiserAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/fz_advertiser/update",
				Handler: fz.FzAdvertiserUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/fz_advertiser/delete",
				Handler: fz.FzAdvertiserDeleteHandler(serverCtx),
			},
		},
	)

	// 飞猪小时报路由
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/fz_hourly_report/list",
				Handler: fz.FzHourlyReportListHandler(serverCtx),
			},
		},
	)

	// 菜鸟基数配置路由
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/cainiao_cardinality/get",
				Handler: config.CainiaoCardinalityGetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/cainiao_cardinality/update",
				Handler: config.CainiaoCardinalityUpdateHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建返点配置
				Method:  http.MethodPost,
				Path:    "/config/rebate/create",
				Handler: config.CreateRebateHandler(serverCtx),
			},
			{
				// 删除返点配置
				Method:  http.MethodPost,
				Path:    "/config/rebate/delete",
				Handler: config.DeleteRebateHandler(serverCtx),
			},
			{
				// 获取返点配置列表
				Method:  http.MethodGet,
				Path:    "/config/rebate/list",
				Handler: config.GetRebateListHandler(serverCtx),
			},
			{
				// 更新返点配置
				Method:  http.MethodPost,
				Path:    "/config/rebate/update",
				Handler: config.UpdateRebateHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建服务费配置
				Method:  http.MethodPost,
				Path:    "/config/servicefee/create",
				Handler: config.CreateServiceFeeHandler(serverCtx),
			},
			{
				// 删除服务费配置
				Method:  http.MethodPost,
				Path:    "/config/servicefee/delete",
				Handler: config.DeleteServiceFeeHandler(serverCtx),
			},
			{
				// 获取服务费配置列表
				Method:  http.MethodGet,
				Path:    "/config/servicefee/list",
				Handler: config.GetServiceFeeListHandler(serverCtx),
			},
			{
				// 更新服务费配置
				Method:  http.MethodPost,
				Path:    "/config/servicefee/update",
				Handler: config.UpdateServiceFeeHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建任务类型
				Method:  http.MethodPost,
				Path:    "/config/tasktype/create",
				Handler: config.CreateTaskTypeHandler(serverCtx),
			},
			{
				// 删除任务类型
				Method:  http.MethodPost,
				Path:    "/config/tasktype/delete",
				Handler: config.DeleteTaskTypeHandler(serverCtx),
			},
			{
				// 获取任务类型列表
				Method:  http.MethodGet,
				Path:    "/config/tasktype/list",
				Handler: config.GetTaskTypeListHandler(serverCtx),
			},
			{
				// 更新任务类型
				Method:  http.MethodPost,
				Path:    "/config/tasktype/update",
				Handler: config.UpdateTaskTypeHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建汇川饿了么数据报表
				Method:  http.MethodPost,
				Path:    "/config/elmhc/create",
				Handler: config.CreateElmHcReportHandler(serverCtx),
			},
			{
				// 删除汇川饿了么数据报表
				Method:  http.MethodPost,
				Path:    "/config/elmhc/delete",
				Handler: config.DeleteElmHcReportHandler(serverCtx),
			},
			{
				// 获取汇川饿了么数据报表列表
				Method:  http.MethodGet,
				Path:    "/config/elmhc/list",
				Handler: config.GetElmHcReportListHandler(serverCtx),
			},
			{
				// 更新汇川饿了么数据报表
				Method:  http.MethodPost,
				Path:    "/config/elmhc/update",
				Handler: config.UpdateElmHcReportHandler(serverCtx),
			},
			{
				// 获取汇川饿了么媒体账户列表
				Method:  http.MethodGet,
				Path:    "/config/elmhc/media/list",
				Handler: config.GetElmHcMediaListHandler(serverCtx),
			},
			{
				// 创建汇川饿了么媒体账户
				Method:  http.MethodPost,
				Path:    "/config/elmhc/media/create",
				Handler: config.CreateElmHcMediaHandler(serverCtx),
			},
			{
				// 删除汇川饿了么媒体账户
				Method:  http.MethodPost,
				Path:    "/config/elmhc/media/delete",
				Handler: config.DeleteElmHcMediaHandler(serverCtx),
			},
			{
				// 更新汇川饿了么媒体账户
				Method:  http.MethodPost,
				Path:    "/config/elmhc/media/update",
				Handler: config.UpdateElmHcMediaHandler(serverCtx),
			},
			{
				// 手动触发汇川饿了么日报
				Method:  http.MethodPost,
				Path:    "/config/elmhc/trigger_daily_report",
				Handler: config.TriggerElmHcDailyReportHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取快手账户报表
				Method:  http.MethodPost,
				Path:    "/report/ks/account",
				Handler: report.GetKsAccountReportHandler(serverCtx),
			},
			{
				// 触发巨量报表任务
				Method:  http.MethodGet,
				Path:    "/report/juliang/trigger",
				Handler: report.TriggerJuliangReportHandler(serverCtx),
			},
			{
				// 获取京橙Cookie
				Method:  http.MethodGet,
				Path:    "/report/jingcheng/cookie",
				Handler: report.GetJingchengCookieHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取京东归因数据
				Method:  http.MethodGet,
				Path:    "/jd/attribution/data",
				Handler: report.GetJDAttributionDataHandler(serverCtx),
			},
			{
				// 导出京东错误统计数据
				Method:  http.MethodGet,
				Path:    "/jd/attribution/export",
				Handler: report.ExportJDErrorCountsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 更新巨量Cookie
				Method:  http.MethodPost,
				Path:    "/update/juliang/cookie",
				Handler: update.UpdateJuliangCookieHandler(serverCtx),
			},
			{
				// 更新京橙Cookie
				Method:  http.MethodPost,
				Path:    "/update/jingcheng/cookie",
				Handler: update.UpdateJingchengCookieHandler(serverCtx),
			},
			{
				// 更新支付宝Cookie
				Method:  http.MethodPost,
				Path:    "/update/zfb/cookie",
				Handler: update.UpdateZfbCookieHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 下载报表文件
				Method:  http.MethodGet,
				Path:    "/download/:filename",
				Handler: download.DownloadReportHandler(serverCtx),
			},
		},
	)

	// =============== ZFB 独立下载接口（无需密码验证，通过 /zfb 反向代理访问）===============
	server.AddRoutes(
		[]rest.Route{
			{
				// ZFB 下载接口
				Method:  http.MethodGet,
				Path:    "/download",
				Handler: zfb.ZfbDownloadHandler(serverCtx),
			},
		},
		rest.WithPrefix("/zfb"),
	)

	// =============== Tanx 淘宝联盟相关接口 ===============
	server.AddRoutes(
		[]rest.Route{
			{
				// 抓取淘宝联盟数据
				Method:  http.MethodPost,
				Path:    "/tanx/fetch_data",
				Handler: tanx.FetchDataHandler(serverCtx),
			},
			{
				// 导出数据并发送邮件
				Method:  http.MethodPost,
				Path:    "/tanx/export_data",
				Handler: tanx.ExportDataHandler(serverCtx),
			},
			{
				// 更新Cookie
				Method:  http.MethodPost,
				Path:    "/tanx/update_cookie",
				Handler: tanx.UpdateCookieHandler(serverCtx),
			},
		},
	)

	// =============== 飞猪时报相关接口 ===============
	server.AddRoutes(
		[]rest.Route{
			{
				// 同步所有媒体数据（OPPO + 小米）
				Method:  http.MethodGet,
				Path:    "/api/fz/sync_all_data",
				Handler: fz.FzSyncAllDataHandler(serverCtx),
			},
			{
				// 同步ADN媒体数据
				Method:  http.MethodPost,
				Path:    "/api/fz/sync_adn_data",
				Handler: fz.FzSyncAdnDataHandler(serverCtx),
			},
		},
	)

	// =============== ulink 转链相关接口 ===============
	server.AddRoutes(
		[]rest.Route{
			{
				// 淘宝单链 deeplink 提取
				Method:  http.MethodPost,
				Path:    "/api/ulink/taobao/extract",
				Handler: ulink.TaobaoExtractHandler(serverCtx),
			},
			{
				// 淘宝批量 deeplink 提取（txt 上传 → Excel 下载）
				Method:  http.MethodPost,
				Path:    "/api/ulink/taobao/batch",
				Handler: ulink.TaobaoBatchHandler(serverCtx),
			},
			{
				// 闲鱼单链 deeplink 提取
				Method:  http.MethodPost,
				Path:    "/api/ulink/xianyu/extract",
				Handler: ulink.XianyuExtractHandler(serverCtx),
			},
			{
				// 闲鱼批量 deeplink 提取（txt 上传 → Excel 下载）
				Method:  http.MethodPost,
				Path:    "/api/ulink/xianyu/batch",
				Handler: ulink.XianyuBatchHandler(serverCtx),
			},
			{
				// 淘宝客活动短链批量获取（txt 上传 → Excel 下载）
				Method:  http.MethodPost,
				Path:    "/api/ulink/activity/batch",
				Handler: ulink.ActivityBatchHandler(serverCtx),
			},
			{
				// 淘宝客活动报表批量查询（Excel 上传 → Excel 下载）
				Method:  http.MethodPost,
				Path:    "/api/ulink/activity/report",
				Handler: ulink.ActivityReportHandler(serverCtx),
			},
			{
				// CPS高佣商品库批量导出（选择商品库 → Excel 下载）
				Method:  http.MethodPost,
				Path:    "/api/ulink/cps/goods",
				Handler: ulink.CpsGoodsBatchHandler(serverCtx),
			},
		},
	)
}
