// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"
	"path/filepath"

	config "media_report/service/api/internal/handler/config"
	download "media_report/service/api/internal/handler/download"
	report "media_report/service/api/internal/handler/report"
	update "media_report/service/api/internal/handler/update"
	"media_report/service/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// 添加静态文件服务
	webDir := filepath.Join("..", "..", "web")
	// 根路径重定向到主页
	server.AddRoute(rest.Route{
		Method: http.MethodGet,
		Path:   "/",
		Handler: func(w http.ResponseWriter, r *http.Request) {
			http.ServeFile(w, r, filepath.Join(webDir, "index.html"))
		},
	})

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建返点配置
				Method:  http.MethodPost,
				Path:    "/config/rebate/create",
				Handler: config.CreateRebateHandler(serverCtx),
			},
			{
				// 删除返点配置
				Method:  http.MethodPost,
				Path:    "/config/rebate/delete",
				Handler: config.DeleteRebateHandler(serverCtx),
			},
			{
				// 获取返点配置列表
				Method:  http.MethodGet,
				Path:    "/config/rebate/list",
				Handler: config.GetRebateListHandler(serverCtx),
			},
			{
				// 更新返点配置
				Method:  http.MethodPost,
				Path:    "/config/rebate/update",
				Handler: config.UpdateRebateHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建服务费配置
				Method:  http.MethodPost,
				Path:    "/config/serviceFeecreate",
				Handler: config.CreateServiceFeeHandler(serverCtx),
			},
			{
				// 删除服务费配置
				Method:  http.MethodPost,
				Path:    "/config/serviceFeedelete",
				Handler: config.DeleteServiceFeeHandler(serverCtx),
			},
			{
				// 获取服务费配置列表
				Method:  http.MethodGet,
				Path:    "/config/serviceFeelist",
				Handler: config.GetServiceFeeListHandler(serverCtx),
			},
			{
				// 更新服务费配置
				Method:  http.MethodPost,
				Path:    "/config/serviceFeeupdate",
				Handler: config.UpdateServiceFeeHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建任务类型
				Method:  http.MethodPost,
				Path:    "/config/tasktype/create",
				Handler: config.CreateTaskTypeHandler(serverCtx),
			},
			{
				// 删除任务类型
				Method:  http.MethodPost,
				Path:    "/config/tasktype/delete",
				Handler: config.DeleteTaskTypeHandler(serverCtx),
			},
			{
				// 获取任务类型列表
				Method:  http.MethodGet,
				Path:    "/config/tasktype/list",
				Handler: config.GetTaskTypeListHandler(serverCtx),
			},
			{
				// 更新任务类型
				Method:  http.MethodPost,
				Path:    "/config/tasktype/update",
				Handler: config.UpdateTaskTypeHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取快手账户报表
				Method:  http.MethodPost,
				Path:    "/report/ks/account",
				Handler: report.GetKsAccountReportHandler(serverCtx),
			},
			{
				// 触发巨量报表任务
				Method:  http.MethodGet,
				Path:    "/report/juliang/trigger",
				Handler: report.TriggerJuliangReportHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 更新聚量Cookie
				Method:  http.MethodPost,
				Path:    "/update/juliang/cookie",
				Handler: update.UpdateJuliangCookieHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 下载报表文件
				Method:  http.MethodGet,
				Path:    "/download/:filename",
				Handler: download.DownloadReportHandler(serverCtx),
			},
		},
	)
}
