// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"media_report/service/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/report/ks/account",
				Handler: GetKsAccountReportHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
